apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - path: /who
        backend:
          serviceName: kface-upload
          servicePort: 80
      - path: /upload
        backend:
          serviceName: kface-upload
          servicePort: 80
      - path: /match/*
        backend:
          serviceName: kface-upload
          servicePort: 80
      - path: /*
        backend:
          serviceName: kface
          servicePort: 80
